### ISSUE TITLE
Rendering errors between vector tile edges

### ISSUE THREAD

**Issue by Baxos04** [mapbox/mapbox-gl-js#1187]
Hello !
I have installed mapboxGL.js and Mapnik on a dedicated server, but I have a bug between 2 tiles, I don't know why but the tiles assemblage fail so I have lines on the screen, see the screenshots for exemple. 
Mapnik serve the vector tiles on pbf format.

This bug cuts the labels too (2nd screenshot).

![capture d ecran 2015-04-27 14 09 21](https://cloud.githubusercontent.com/assets/2789124/7364920/00e257b0-ed8c-11e4-801a-59b642d77d58.png)
![capture d ecran 2015-04-27 13 58 50](https://cloud.githubusercontent.com/assets/2789124/7364925/075df16c-ed8c-11e4-8ece-92d1e9861807.png)

What can I do to fix this?

Thank you and sorry for my english.

**Comment by ansis** [comment]
It looks like the data in your vector tiles is clipped exactly to the tile boundaries. Increasing the buffer for the vector tiles should fix this.

I think the label issue is the same as this: https://github.com/mapbox/mapbox-gl-js/issues/757

**Comment by Baxos04** [comment]
Hello,
Thank you for your answer, but i have already tested that, currently the buffer-size parameter is set to 128 (I have tested 256 and 512 but nothing works) I have also set the avoid-edges at true but the bug persists :/

**Comment by ansis** [comment]
@springmeyer is buffer-size the right parameter for adding buffers around edges to vt layers?

**Comment by springmeyer** [comment]
@ansis - yes, that is correct. And I agree that this looks fixable by using at least a buffer-size of >= 1 for Mapnik.

**Comment by Baxos04** [comment]
@ansis @springmeyer Thanks a lot for your suggestions. Indeed buffer parameter did the trick for me but I had to set it up for layer and not at the map level (as indicated in the doc).

**Comment by jfirebaugh** [comment]
@Baxos04 Can you link to the doc that suggested buffering at the map level? We can update that to make it clearer.

**Comment by Baxos04** [comment]
@jfirebaugh Yep : https://github.com/mapnik/mapnik/wiki/XMLConfigReference
The buffer-size is an attribute of map object, not in the layer object.

**Comment by baxford** [comment]
this may not be the case, but I have had a similar problem, and found that it was because the building shadows (the dark edges on the buildings) had a higher z-index than the buildings. This meant that where the polygons were clipped at the tile boundaries would be treated as a building edge and rendered as such.
A workaround is to give the building shadow a lower z-index so that when it is created for a tile boundary, it will be overlapped by the remainder of the building on the adjacent tile.

**Comment by nextstopsun** [comment]
Same problem here - I've had rendering artefacts on tile edges until I found this issue. Got distracted by Mapnik docs, where `buffer-size` attribute is on the `Map` object, and not on the `Layer`. Also setting it on the `Map` object doesn't seem to work.
