### ISSUE TITLE
easeTo panning does not work properly when zoom changes

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1744]
... while `flyTo` *does* work

https://jsfiddle.net/vyaLssek/

**Comment by lucaswoj** [comment]
We should add test cases for easeTo and flyTo with pitch

**Comment by lucaswoj** [comment]
@1ec5 Can you provide a little more context for "needs port from C++"? Does this remind you of a gl-native bug that was fixed?

**Comment by 1ec5** [comment]
I think I misread “easeTo panning” as “easeTo padding”. Looking at the fiddle you posted, I’m not sure I see what the bug is. Can you elaborate?

**Comment by lucaswoj** [comment]
This fiddle makes the bug easier to understand: https://jsfiddle.net/4jusfhp2/

`easeTo` is passed `center: [0, 0]` but the map actually centers on some point in Alaska. Compare to the behavior when

 - a zoom is not passed to `easeTo`
 - `flyTo` is used instead of `easeTo`

**Comment by 1ec5** [comment]
Interesting. mapbox-gl-native doesn’t have this bug. [Its `easeTo()` implementation](https://github.com/mapbox/mapbox-gl-native/blob/48504baa9134020c57bb899f290557b4249a2d6d/src/mbgl/map/transform.cpp#L236) doesn’t do anything particularly special around pitch, but you might have a look at whether the transforms differ in some way during the animation.

**Comment by khashashin** [comment]
It's still throws error:
```
state.map.flyTo({
	center: e.currentTarget.dataset.location.split(','),
	zoom: 15, // throws error
	duration: 3000
});
```
![image](https://user-images.githubusercontent.com/17837758/68041599-350e3a00-fcd1-11e9-9ce1-91df73456d18.png)

```
Uncaught TypeError: this._onEaseFrame is not a function
    at r.i._renderFrameCallback (camera.js:1060)
    at ko.run (task_queue.js:52)
    at r._render (map.js:1926)
    at map.js:2051
i._renderFrameCallback @ camera.js:1060
ko.run @ task_queue.js:52
r._render @ map.js:1926
(anonymous) @ map.js:2051
requestAnimationFrame (async)
frame @ browser.js:35
r.triggerRepaint @ map.js:2049
r._update @ map.js:1891
(anonymous) @ map.js:384
St.fire @ evented.js:115
i._fireMoveEvents @ camera.js:775
(anonymous) @ camera.js:1007
i._renderFrameCallback @ camera.js:1060
ko.run @ task_queue.js:52
r._render @ map.js:1926
(anonymous) @ map.js:2051
requestAnimationFrame (async)
frame @ browser.js:35
r.triggerRepaint @ map.js:2049
r._update @ map.js:1891
r._requestRenderFrame @ map.js:1903
i._ease @ camera.js:1053
i.flyTo @ camera.js:991
mountDetail @ ./drones.html.js:260

```

**Comment by Yanonix** [comment]
Hi @khashashin ,
I presume you have the same error as me, as I can see by your call stack.
I have found and fix the problem, just few minutes ago.
You shouldn't call a map camera transition (`map.easeTo`, `flyTo`, ..) while the context is in a map event (such as` moveend`, ...). You have to deferred your new camera transition calls, by using `requestAnimationFrame` or `timeout`.

There is a problem with calling inside an event while the user is interacting. This calls a double `map.stop()` and makes a difference between `map._easeFrameId` and the current `map._requestRenderFrame` queue (which in this case contains multiple ease animation).
