### ISSUE TITLE
Multipolygons disappearing from map at certain zoom levels.

### ISSUE THREAD

**Issue by lcapel** [mapbox/mapbox-gl-js#2704]
I have a TopoJSON map of europe which I'm loading into mapbox (0.19.1). I have an issue where one of my country layers (Spain) disappears at certain zoom levels. I think this could also be an earcut issue  (similar to https://github.com/mapbox/mapbox-gl-js/issues/2657) as the issue is not present in 0.18.0.

See the attached gif

![choro](https://cloud.githubusercontent.com/assets/870335/15924227/ef10aff8-2e28-11e6-88c9-8074e04d1ec5.gif)

**Comment by mourner** [comment]
Yeah, it's likely an earcut issue. Can you share the data you're using?

**Comment by mourner** [comment]
Or better, a minimal JSFiddle test case that reproduces the issue.

**Comment by lcapel** [comment]
I made a quick and dirty example using GeoJSON instead of TopoJSON. It still show the same issue for Spain at some zoom levels. http://jsbin.com/zasuduquqe/edit?html,output

**Comment by mourner** [comment]
@Icapel thanks! I'll investigate.

**Comment by mourner** [comment]
I pushed a PR to geojson-vt that should fix the issue: https://github.com/mapbox/geojson-vt/pull/63. Can you check if it fixes all issues for you? You would need to do `npm install mapbox/geojson-vt#vt2` and then `npm run build-min` to generate a fixed build in the GL JS repo.

**Comment by jfirebaugh** [comment]
Let's keep this open until we explicitly bump the minimum geojson-vt version in package.json.

**Comment by mourner** [comment]
Right. Published geojson-vt 2.2.0 with the change now.

**Comment by nellessen** [comment]
I am still seeing exactly the same issue with mapbox gl-js v0.41.0.

**Comment by cs09g** [comment]
@nellessen I guess, you're facing the same problem if you have polygons which has lots of coordinates. The solution is modify the mapbox engine where limits striping out the polygons for earcut performance.
remove this condition block or increase `maxRings` up to the number of max coordinates.
https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/classify_rings.js#L39
