### ISSUE TITLE
Support icon-color for non-SDF icons

### ISSUE THREAD

**Issue by ivelander** [mapbox/mapbox-gl-js#3605]
We have a use case that requires the ability to use icons for data-driven shapes as well as data-driven coloring of those icons. Currently we can get half of this functionality from the `circle` layer type and  half from the `symbol` layer type. We have a hacked solution that merges the basic features of both on a fork of mapbox-gl-js (along with a style-spec and shader fork)...

https://github.com/ivelander/mapbox-gl-js

It would be great to be able to get off this fork, something we could do if support was added for `icon-color` for non-SDF icons.

**Comment by ivelander** [comment]
Here is an example of the result I am after, this uses the fork linked in the first comment to use a sprite sheet texture and a property based color.

<img width="576" alt="screen shot 2016-11-13 at 9 51 00 am" src="https://cloud.githubusercontent.com/assets/1337082/20247336/d0c247a8-a986-11e6-9e0a-af72074083be.png">

**Comment by lucaswoj** [comment]
This would be great to support on `fill-pattern` and `line-pattern` too 😄

**Comment by rhagigi** [comment]
Just in case this helps anyone -- I solved this issue on my map by using a custom icon font (I used http://fontastic.me but FontAwesome or anything else will work just the same). Just upload the font to mapbox studio and use the text-font, text-color, text-size, etc styling options for the geoJson layer and just use no icon. You can do some pretty awesome stuff with that and it has the added benefit of making it much easier to set up an icon baseline size and scale it up or down (vs my previously uploaded SVGs to mapbox studio which all ended up slightly different sizes).

**Comment by aidanlister** [comment]
@rhagigi any chance you can post a full example / screenshot?

**Comment by rhagigi** [comment]
Sure thing, I'll put something together when I get home.

**Comment by rhagigi** [comment]
![image](https://cloud.githubusercontent.com/assets/1672482/24457343/f3bedb70-1463-11e7-9019-66b5690a924f.png)

The way I'm achieving it is fairly simple. As I mentioned before, simply create a font using fontastic or another font generation service/build-tool, or use an existing icon font like [fontawesome](http://fontawesome.io/) or [material-icons](https://material.io/icons/). Then:

1) Upload that font on the [Mapbox Studio Font Page](https://www.mapbox.com/studio/styles/fonts). 
    a) I think I had to also use the font on some layer in the map to get it to come down with the map and be usable. Could be a fake layer or just a layer you're not even really using in your style, like maybe "airport labels" or something obscure. Make a note of what the font is called there, you'll need it later
[see example screenshot](https://cloud.githubusercontent.com/assets/1672482/24458011/bdc0dae4-1465-11e7-8310-362a250b5bab.png)

2) Add a GeoJSON source to the map as usual

```javascript
 map.addSource('MySourceId', {
        type: 'geojson',
        data: geoJson
      });
```

3) Add a `symbol` layer to the map to show that source, using our font and a bunch of layout/styling tricks to get it working to your tastes:

```javascript
map.addLayer({
        id: 'MyLayerId',
        type: 'symbol',
        source: 'MySourceId',
        layout: {
          'text-line-height': 1, // this is to avoid any padding around the "icon"
          'text-padding': 0,
          'text-anchor': bottom, // change if needed, "bottom" is good for marker style icons like in my screenshot,
          'text-allow-overlap': true, // assuming you want this, you probably do
          'text-field': iconString, // IMPORTANT SEE BELOW: -- this should be the unicode character you're trying to render -- NOT the character code but the actual character,
          'icon-optional': true, // since we're not using an icon, only text.
          'text-font': ['FontAwesome Regular'], // see step 1 -- whatever the icon font name,
          'text-size': 18 // or whatever you want -- unfortunately can't be data driven
        },
        paint: {
          'text-translate-anchor': 'viewport', // up to you to change this -- see the docs
          'text-color': '#00FF00" // whatever you want -- can even be data driven using a `{featureProperty}`,
        }
      });
```

For more layout/paint properties you can use (like pitch/rotation styling, etc) and more info, [visit the Mapbox Style spec page for symbol layers](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol) 

4) In order to set the text field, you need to actually have a string value of the icon you want. If you already know the character code for the one you need, you can just hardcode it and use `String.fromCharCode` to get a string value from that character code from the font css. For example, [fa-calendar is `"\f073"`](https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L518). 

But, that can be hard when you don't know what the character will be in the font and you want to use the "classname" version for this, like `fa-calendar` or `fa-plane` or whatever. This makes you more resilient in case you upgrade font versions, as the underlying character-code mapping may change. Make sure you load the font in your CSS as well for this technique -- I use fontawesome on my site anyway so it wasn't extraneous.

This is kinda-font-awesome specific, as they load the character using CSS into the `:before` `content` based on the classname ([fa-calendar example](https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L518)), but you can use a similar technique for most icon fonts. I wrapped my function in lodash memoize as once you call this once for a classname, you should never need to call it again.

```javascript
const getFontAwesomeStringFromClassname = _memoize((className) => {
  const element = document.createElement('i');
  element.className = 'fa ' + className; // font-awesome specific where `className`==="calendar"
  element.style.display = 'none'; //  or not
  document.body.appendChild(element);
  const contentValue = window.getComputedStyle(
    element, ':before'
  ).getPropertyValue('content');
  document.body.removeChild(element);
  return contentValue;
});
```

You can then pass that returned contentValue into `text-field` or -- if you want, use it in your GeoJSON source to use different icons for different features, and use the `{someFeatureProperty}` syntax to grab the textField from each feature property. I suggest a similar approach for the `text-color` property if you want to drive it based on data. 

Unfortunately, I'm not sure if mapbox-gl supports data-driven styling yet for font-size (they might now), so I just used multiple layers with filters on them to do dynamic sizing (e.g.: one layer size 40 and one layer size 20, with filters for the feature type). 

Hopefully that wasn't too much craziness and I didn't skip anything important. Let me know if you have any questions about all that.

**Comment by aidanlister** [comment]
That's great Royi, thanks!

**Comment by ivelander** [comment]
We are using a similar strategy as well. I'd be curious if anyone (perhaps the mapbox folks) have any input on potential performance or stability concerns with this strategy. I know there is a lot of logic in the text placement logic to manage collisions, positioning in relation to the icon, etc. Our apps can result in a lot of data on the map, so performance quickly becomes a concern with everything we are doing (part of the appeal of mapbox-gl in the first place).

**Comment by aidanlister** [comment]
We've solved this a different way!

We've used circles and icons as separate layers ... see this:

```
    icon_layer = {
        "id": "images",
        "type": "symbol",
        "source": "markers",
        "layout": {
            "icon-image": "{icon}-15",
            "icon-allow-overlap": True,
            "icon-ignore-placement": True,
            "icon-size": {
                "base": 1,
                "type": "exponential",
                "stops": [
                    [10, 0],
                    [12, 0.8],
                    [15, 0.8],
                    [18, 1]
                ]
            },

        }
    }
    circle_layer = {
        "id": "markers",
        "type": "circle",
        "source": "markers",
        "paint": {
            'circle-radius': {
                'property': 'task-priority',
                'type': 'categorical',
                'stops': [[1, 5], [5, 5], [10, 10]],
            },
            'circle-color': {
                'property': 'task-status',
                'type': 'categorical',
                'stops': list(qs.model.STATUS_CHOICES_COLOURS.items()),
            },
            'circle-stroke-width': 1,
            'circle-stroke-color': '#fff',
            'circle-stroke-opacity': 1,
        }
    }
    layers = [circle_layer, icon_layer]
```

This is what it looks like:

![bc24bf1a-1565-11e7-8daf-db1854c7a42b](https://cloud.githubusercontent.com/assets/54896/24493188/a96145ce-1579-11e7-94b6-ffaea31a8772.gif)

**Comment by davidascher** [comment]
@rhagigi Thanks for the detailed description.  I'm almost there.

I'm finding that even though I have added FontAwesome (or Material Icons) as a font to my Mapbox style, and even though some version of that font gets downloaded by the mapbox component, no markers show up. 

If i use a font that I know exists like `Arial Unicode MS Bold` then I see their (ugly ;) letters.

I believe the font isn't being properly downloaded, based on the network traffic:

<img width="639" alt="screenshot 2017-04-23 12 12 11" src="https://cloud.githubusercontent.com/assets/51278/25316544/2ad1562e-281e-11e7-8965-1c04733e1021.png">

56 bytes seems a bit short.

Any suggestion how to debug this?

(it'd be lovely if mapbox just published these two very common and openly licensed fonts)

**Comment by davidascher** [comment]
Hmm, reading on the API (https://www.mapbox.com/api-documentation/#fonts) it seems that API call is just getting a single glyph, which should be fine.  Maybe it's just my character lookup isn't correct.

**Comment by davidascher** [comment]
Figured it out.  The mapping from icon to a string was where I was failing.  

For the next people who run into this issue, here are the incantations to map from a font-awesome or Material Design Icons to a string that will fit in with @rhagigi's method above.

For Font-Awesome, find the icon like, e.g. http://fontawesome.io/icon/camera/, you'll notice it says it is at Unicode location `f030`.  

<img width="464" alt="screenshot 2017-04-23 13 23 44" src="https://cloud.githubusercontent.com/assets/51278/25317171/354c77a0-2828-11e7-9d9a-94fe60059275.png">

The string you want is therefore: `String.fromCharCode("0xf030")`. 

For Material Icons, you'll notice in the instructions for Web Font under "IE usage" that the entity is 
`&#xE8FC;`.  

<img width="595" alt="screenshot 2017-04-23 13 22 08" src="https://cloud.githubusercontent.com/assets/51278/25317160/e283acdc-2827-11e7-8aa3-551d51b1ef69.png">

That corresponds to using the string `String.fromCharCode("0xe8fc")`.

It's definitely a manual mapping, but it helped me out.

**Comment by rohanrichards** [comment]
I was running into an issue trying to use Glyphicons pro icon packs inside of an Ionic project using Mapbox GL.
In Ionic, typescript forces `String.fromCharCode()` to be accept only a number, so you run into issues when you need to map to the higher end Unicode characters. For the character I wanted (shown as UTF+E592 on the Glyphicons website) I was trying `String.FromCharCode(592)' and just getting blank characters. And I was unable to use e592 or other variations due to the above typing limitations.

e.g 0xe592 is not a number so you get compilation errors. See: [MDN FromCharCode - Getting it to work with higher values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode)

The solution was to actually use `String.fromCodePoint()` which accepts an octet: `String.fromCodePoint(0xe592)`

**Comment by Kilatsat** [comment]
The biggest issue I have encountered using non-SDF icons is that `icon-halo-XXX` options do not work. non-SDF with valid a-channel seem to work as expected with `icon-color`

**Comment by stdmn** [comment]
@davidascher @rhagigi Trying your methods to use Google's Material Icons [I've also tried with Font Awesome] and I've not been able to get the icons to show up. I've tested the Material Icons on other parts of the page (ie: <img width="22" alt="screen shot 2018-06-04 at 6 27 09 pm" src="https://user-images.githubusercontent.com/17128916/40945006-ed29e82a-6824-11e8-862f-b70f67118b4c.png">)  without problems and used your exact coding.

The icon is also showing up in console after using String.formCharCode(). 
<img width="328" alt="screen shot 2018-06-04 at 6 23 35 pm" src="https://user-images.githubusercontent.com/17128916/40944899-789cc720-6824-11e8-8ef2-28334810179e.png">

Here's the code: [
<img width="381" alt="screen shot 2018-06-04 at 6 25 09 pm" src="https://user-images.githubusercontent.com/17128916/40944940-a7029dc4-6824-11e8-933e-e241481fb092.png">
](url)

@rhagigi Does this method only work using Mapbox Studio-hosted fonts? Or can I use the Google Material Icons CDN?

**Comment by brendanmc6** [comment]
@aidanlister I've tried everything and can't o reproduce your method for displaying icons on top of circles. In my case, circles _always_ overlap the Maki symbols no matter which order I add them or which method I use for adding/moving layers, and regardless of the layout settings that I pass. On their own, both circles and icon symbols work as expected.

I have a very simple problem that was very easily solved with Leaflet. I just need dynamic icons on top of a dynamic color. By dynamic I mean, my app pulls a layer object, each containing a different `icon` and `color `property that was chosen by the user, then adds the associated markers to the map. This was very easy with leaftlet awesome-markers.

Since I can get the circles to display properly, I thought to iterate over my features a second time using `querySourceFeatures()` and then add `new Marker` on top, however my query always returns an empty array, AND I can't figure out how to pull an icon from material icons and use it as the element.

If anyone has some advice I would VERY much appreciate it, and will be sure to write up a how-to here for future devs struggling with the same issue.

**Comment by everhardt** [comment]
@Kilatsat I can't reproduce your comment that `icon-color` does work with images with an alpha channel. I tried with png files that are partially transparent. Am I doing something wrong?

**Comment by Kilatsat** [comment]
@everhardt I should have been more clear in my previous response: it appears to respect a=0. I did not test semitransparent images.

**Comment by everhardt** [comment]
@Kilatsat I'm sorry, I'm still not clear on what you are saying. Do you say that it's possible to change the color of certain non-SDF images or are you saying that it is possible to make an image invisible (completely transparent, alpha = 0) by changing the `icon-color` paint property to some value.

I fail to achieve either, but I'm interested in the former..

**Comment by Kilatsat** [comment]
@everhardt I can help you modify an existing example to illustrate the point I was originally making:

1. Start from the code contained in https://www.mapbox.com/mapbox-gl-js/example/add-image/
2. Modify line 29 to read ```map.addImage('cat', image, { sdf: true });```
3. In the `map.addLayer` add a new section that reads ```"paint": {"icon-color": "orange"}```

This modification causes the cat to appear `orange` instead of the default `black` even though the cat image is non-SDF.

**Comment by everhardt** [comment]
@Kilatsat Thanks a lot, that is exactly what I was looking for!

**Comment by ahmedkhan1039** [comment]
I have thoroughly investigated the issue. The problem is in the use of `map.loadImage()` function. If we reference a file by its path i-e `map.loadImage('../../cat.png')` then even if you make `{ sdf: true }`, you will not able to change the **color** and other **related features**.  If you want to change color you have to convert the image into its base64 equivalent. `const catImg = require('../../cat.png');` and then use the `map.loadImage()` function to load it. Now if you do `{ sdf: true }` you can successfully change the **color** or **related features**.

**Comment by danger89** [comment]
@stdmn You can download all pdb files from here (including my addition of Font Awesome 5 Free solid icons):
https://github.com/danger89/fonts/tree/gh-pages

**Comment by sansumbrella** [comment]
Piggy-backing on this issue since I recently ran into a need for coloring icons based on data. Currently working around it by using multiple SVGs, though I like the font-awesome workaround suggested above.

Coloring icons would be an excellent feature to add for the cost of a single multiply in our shader and 24 bits of color data.

**Comment by strech345** [comment]
> @everhardt I can help you modify an existing example to illustrate the point I was originally making:
> 
> 1. Start from the code contained in https://www.mapbox.com/mapbox-gl-js/example/add-image/
> 2. Modify line 29 to read `map.addImage('cat', image, { sdf: true });`
> 3. In the `map.addLayer` add a new section that reads `"paint": {"icon-color": "orange"}`
> 
> This modification causes the cat to appear `orange` instead of the default `black` even though the cat image is non-SDF.

Why this possiblity is not documented? Me help this information a lot!

**Comment by HarelM** [comment]
For anyone reading this I have came across the following solution (haven't tried it yet), which is different than using font awsome characters (which I think is problematic if you read the style from a json file without replacing anything like I need to):
https://www.npmjs.com/package/@elastic/spritezero
https://www.npmjs.com/package/@elastic/spritezero-cli
This fork can create an sdf image from SVG files.
These generated files can be used as sprites for mapbox-gl to receive the required behavior.
Here's an example (I didn't write it just came across it):
http://www.npeihl.com/maki-sdf-sprites/
I have looked at the code and it basically loads the image to `Image` DOM element and adds a single sdf image using `addImage(... { sdf: true})`.
I hope it can be used as a sprite link instead but I haven't tried it yet.
@nickpeihl can you confirm?

**Comment by nickpeihl** [comment]
> I hope it can be used as a sprite link instead but I haven't tried it yet.
> @nickpeihl can you confirm?

@HarelM Are you asking if it's possible to include a URL to the spritesheet in a style definition? I think that should work, because the spritesheet.json file ([example](https://unpkg.com/@elastic/maki@6.1.0/dist/sprite@1.json)) includes `{ sdf: true }` for each sprite.

**Comment by HarelM** [comment]
@nickpeihl thanks for the info!
Here's an example of a colored icon using your example sdf sprite.
https://stackblitz.com/edit/mapbox-simple-map-sdf-sprite
![image](https://user-images.githubusercontent.com/3269297/76164636-2b05b780-6159-11ea-9a3f-f92fe822c47b.png)
The only caveat I found is that spritezero-cli can't be installed on windows. It can be installed using ubuntu linux container with docker, but it's a hassle...

**Comment by fxi** [comment]
Here is a simple docker image to convert a folder of `./svg/*.svg` files into a folder of `./dist/sprite*`, with `{sdf: true}` set for each sprite :  

`docker run -v $(pwd)/dist:/dist -v $(pwd)/svg:/svg fredmoser/svg_to_sprite:latest`

Repo : [svgToSprite](https://github.com/fxi/svgToSprite)

**Comment by cablehead** [comment]
> Hopefully that wasn't too much craziness and I didn't skip anything important. Let me know if you have any questions about all that.

This is a very helpful work around, thanks @rhagigi! 

> 1. Upload that font on the [Mapbox Studio Font Page](https://www.mapbox.com/studio/styles/fonts).
>    a) I think I had to also use the font on some layer in the map to get it to come down with the map and be usable. Could be a fake layer or just a layer you're not even really using in your style, like maybe "airport labels" or something obscure

For shame mapbox :/

**Comment by ibesora** [comment]
We support vector icons with params that allow changing colors since `v3.9.0`
See an example here: https://docs.mapbox.com/mapbox-gl-js/example/custom-colorized-vector-icons/
